source 'https://rubygems.org'

gem 'rake'
gem 'github-markdown', require: 'github/markdown'
gem 'jekyll'
gem 'sanitize'
gem 'github-linguist', require: 'linguist'
gem 'jekyll-html-pipeline'
gem 'pygments.rb'
gem 'rinku'
gem 'extended-markdown-filter'
gem 'redcarpet'
gem 'jekyll-autolink_email'
